### ISSUE TITLE
Custom notification Icon not showing

### ISSUE THREAD

**Issue by GamingSauce** [hippogamesunity/SimpleAndroidNotificationsPublic#33] opened 2018-11-05 10:15 UTC
I cannot manage to make the custom large icon to work.
1.I added the icons I want to use to the .aar file in the res folder
2.I called the SendCustom function with the name of the file example:"MissionIcon", also tried "MissionIcon.png"

**Comment by GamingSauce** [comment] 2018-11-17 16:54
@hippogamesunity Is this going to be fixed?

**Comment by hippogamesunity** [comment] 2018-11-19 20:09
I know it can be important for you, but I can't fix it right now. Please be patient and wait for the resolution.

**Comment by hippogamesunity** [comment] 2018-12-05 19:27
I've got Unity 2018, a new clean project with clean asset setup. Then I simply change Large icon from "app_icon" to "anp_star" (built-in images basically used for small icons, you can find them inside AAR). And it works like expected. I would recommend you to start with this setup, then try placing different images to resources. You need to refer to Android docs to learn about namings, supported types and image dimensions.

![image](https://user-images.githubusercontent.com/7318172/49538617-eac3e380-f8dc-11e8-9c0d-2fd188d5401c.png)
![image](https://user-images.githubusercontent.com/7318172/49538456-86a11f80-f8dc-11e8-807f-ba9b7d83e6c3.png)

**Comment by hippogamesunity** [comment] 2018-12-05 20:28
Maybe you need this setting? Found it on my Android 8 phone in Notification settings.
![image](https://user-images.githubusercontent.com/7318172/49542027-75104580-f8e5-11e8-8a75-655bf8d7872e.png)

**Comment by hippogamesunity** [comment] 2018-12-05 20:33
Please try to set NotificationParams.NotificationImportance and let me know if it's ok!

**Comment by hippogamesunity** [comment] 2018-12-06 14:43
Closing issue, not a bug. For everyone - just refer to manual.pdf included!

**Closed as completed by hippogamesunity** 2018-12-06 14:43 UTC
Labels: help wanted
